[project]
name = "png2svg"
version = "0.1.0"
description = "Convert PNG images to SVG using a hexagonal grid"
readme = "README.md"
authors = [
    { name = "coline m", email = "coline.mouze@gmail.com" }
]
requires-python = ">=3.14"
dependencies = [
    "pillow>=12.3.0",
]

[project.scripts]
png2svg = "png2svg:main"

[build-system]
requires = ["uv_build>=0.12.17,<0.13.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "marimo>=0.25.1",
    "pytest>=9.1.1",
    "ruff>=0.16.10",
]
